name: pull-request

on:
  pull_request:
    branches: ["main"]

permissions: {}

# jobs:
#   check-commit:
#     runs-on: ubuntu-latest
#     steps:
#       - uses:  ytanikin/PRConventionalCommits@1.1.0
#         with:
#           add_label: 'false'
#           task_types: '["feat","fix","doc","perf","refactor","style","test","chore","ci","build","revert"]'
          
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Lint commits
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        uses: ./.github/actions/lint-commit

  build:
    needs:
      - commitlint
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/test.yaml
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    secrets: inherit